<?php


function commerce_dotpay_help($path, $arg) {
	switch ($path) {
		case "admin/help/ah":
			return '<p>' . t("Integrate dotpay payment method") . '</p>';
			break;
	}
}

function commerce_dotpay_menu() {
	$items['dotpay/callback'] = array(
		'page callback' => 'commerce_dotpay_callback',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	return $items;
}


function commerce_dotpay_callback() {
	return false;
}


function commerce_dotpay_commerce_payment_method_info() {
	$payment_methods = array();
	$payment_methods['commerce_dotpay_payment'] = array(
		'title' => t('Dotpay credit card payment solution'),
		'display_title' => t('Pay with a dotpay'),
		'description' => t('Dotpay payment solution'),
		'active' => TRUE,
	);
	return $payment_methods;
}


function commerce_dotpay_payment_settings_form($settings = NULL) {

	$settings = (array) $settings + commerce_dotpay_paynment_default_settings();

	$form = array();

	$form['identifier'] = array(
		'#type' => 'textfield',
		'#title' => t('identifier'),
		'#description' => t('description identifier'),
		'#default_value' => $settings['identifier'],
		'#required' => TRUE,
	);

	$form['pid'] = array(
		'#type' => 'textfield',
		'#title' => t('pid'),
		'#description' => t('description pid'),
		'#default_value' => $settings['pid'],
		'#required' => TRUE,
	);

	$form['payment_url'] = array(
		'#type' => 'textfield',
		'#title' => t('payment_url'),
		'#description' => t('description payment_url'),
		'#default_value' => $settings['payment_url'],
		'#required' => TRUE,
	);


	return $form;
}

function commerce_dotpay_paynment_default_settings(){
	return array(
		'identifier' => '',
		'pid' => '',
		'payment_url' => ''
	);
}


