<?php

DEFINE('DOTPAY_PAYMENT_TYPE', '0');
DEFINE('DOTPAY_API_VERSION', 'dev');


function commerce_dotpay_help($path, $arg) {
	switch ($path) {
		case "admin/help/ah":
			return '<p>' . t("Integrate dotpay payment method") . '</p>';
			break;
	}
}

function commerce_dotpay_menu() {
	$items['dotpay/callback/%commerce_payment_method_instance'] = array(
		'page callback' => 'commerce_dotpay_callback',
		'psge arguments' => array(1),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	return $items;
}


function commerce_dotpay_callback($abc) {


//		if(!isset($_POST['id']) ||
//		   !isset($_POST['control']) ||
//		   !isset($_POST['signature']) ||
//		   !isset($_POST['operation_original_amount'])
//		){
//			echo 'Incomplete request from dotpay';
//			return true;
//		}
//
//		$order = commerce_order_load(10);
//		$payment_method = commerce_payment_method_instance_load($order->data['payment_method']);
//		$hash = commerce_dotpay_calculate_hash($payment_method['settings']['pid'], $_POST);
//
//		if($_POST['signature'] == $hash &&
//		   $_POST['id'] == $payment_method['settings']['identifier']){
//			echo 'Signature does not mach';
//			return true;
//		}
//
		if(!$_POST['operation_status'] == 'completed'){
			commerce_dotpay_process_transaction();
			echo 'OK';
			return true;
		}



	error_log("DOTPAY-pid: ". print_r($payment_method['settings']['pid'], true) );
	error_log("DOTPAY-hast: ". print_r($hash, true) );


	error_log("DOTPAY-POST: ". print_r($_POST, true) );
	echo 'Error occure';
	return true;
}


function commerce_dotpay_process_transaction(){
	var_dump(commerce_payment_transaction_load(2));
	$order = commerce_order_load(10);

}

function commerce_dotpay_calculate_hash($pid, $vars){
	$string = $pid .
		(isset($vars['id']) ? $vars['id'] : '').
		(isset($vars['operation_number']) ? $vars['operation_number'] : '').
		(isset($vars['operation_type']) ? $vars['operation_type'] : '').
		(isset($vars['operation_status']) ? $vars['operation_status'] : '').
		(isset($vars['operation_amount']) ? $vars['operation_amount'] : '').
		(isset($vars['operation_currency']) ? $vars['operation_currency'] : '').
		(isset($vars['operation_withdrawal_amount']) ? $vars['operation_withdrawal_amount'] : '').
		(isset($vars['operation_commission_amount']) ? $vars['operation_commission_amount'] : '').
		(isset($vars['operation_original_amount']) ? $vars['operation_original_amount'] : '').
		(isset($vars['operation_original_currency']) ? $vars['operation_original_currency'] : '').
		(isset($vars['operation_datetime']) ? $vars['operation_datetime'] : '').
		(isset($vars['operation_related_number']) ? $vars['operation_related_number'] : '').
		(isset($vars['control']) ? $vars['control'] : '').
		(isset($vars['description']) ? $vars['description'] : '').
		(isset($vars['email']) ? $vars['email'] : '').
		(isset($vars['p_info']) ? $vars['p_info'] : '').
		(isset($vars['p_email']) ? $vars['p_email'] : '').
		(isset($vars['channel']) ? $vars['channel'] : '').
		(isset($vars['channel_country']) ? $vars['channel_country'] : '').
		(isset($vars['geoip_country']) ? $vars['geoip_country'] : '');
	return hash('sha256', $string);
}

function commerce_dotpay_commerce_payment_method_info() {
	$payment_methods = array();
	$payment_methods['commerce_dotpay_payment'] = array(
		'base' => 'commerce_dotpay_payment',
		'title' => t('Dotpay credit card payment solution'),
		'display_title' => t('Pay with a dotpay'),
		'description' => t('Dotpay payment solution'),
		'terminal' => FALSE,
		'offsite' => TRUE,
		'offsite_autoredirect' => false,
		'active' => TRUE,
	);
	return $payment_methods;
}


function commerce_dotpay_payment_settings_form($settings = NULL) {

	$settings = (array) $settings + commerce_dotpay_paynment_default_settings();

	$form = array();

	$form['identifier'] = array(
		'#type' => 'textfield',
		'#title' => t('identifier'),
		'#description' => t('description identifier'),
		'#default_value' => $settings['identifier'],
		'#required' => TRUE,
	);

	$form['pid'] = array(
		'#type' => 'textfield',
		'#title' => t('pid'),
		'#description' => t('description pid'),
		'#default_value' => $settings['pid'],
		'#required' => TRUE,
	);

	$form['payment_url'] = array(
		'#type' => 'textfield',
		'#title' => t('payment_url'),
		'#description' => t('description payment_url'),
		'#default_value' => $settings['payment_url'],
		'#required' => TRUE,
	);


	return $form;
}

function commerce_dotpay_paynment_default_settings(){
	return array(
		'identifier' => '',
		'pid' => '',
		'payment_url' => 'https://ssl.dotpay.pl/test_payment/'
	);
}

function commerce_dotpay_payment_redirect_form($form, &$form_state, $order, $payment_method) {

	if (empty($payment_method['settings']['identifier'])) {
		drupal_set_message(t('Dotpay is not configured for use. Merchant id has not been specified.'), 'error');
		return array();
	}

	if (empty($payment_method['settings']['pid'])) {
		drupal_set_message(t('Dotpay is not configured for use. Merchant pid has not been specified.'), 'error');
		return array();
	}

	$settings = array(
		// Return to the previous page when payment is canceled
		'cancel_return' => url('checkout/' . $order->order_id . '/payment/back/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
		// Return to the payment redirect page for processing successful payments
		'return' => url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
		// Url to get POST result of payment.
		'merchant_url' => url('dotpay/callback/'. $payment_method['instance_id'], array('absolute' => TRUE)),
	);

	return commerce_dotpay_order_form($form, $form_state, $order, $payment_method + $settings );
}

function commerce_dotpay_order_form($form, $form_state, $order, $payment_method){
	$wrapper = entity_metadata_wrapper('commerce_order', $order);
	$lang = commerce_dotpay_get_and_validateLanguage();

	$form['#action'] = $payment_method['settings']['payment_url'];

	$data = array(
		'id' => $payment_method['settings']['identifier'],
		'amount' => $wrapper->commerce_order_total->amount->value(),
		'currency' => $wrapper->commerce_order_total->currency_code->value(),
		'control' => $order->order_id,
		'description'  => t('Order @order_number at @store', array('@order_number' => $order->order_id, '@store' => variable_get('site_name', url('<front>', array('absolute' => TRUE))))),
		'lang' =>$lang,
		'URL' => $payment_method['return'],
		'URLC' => $payment_method['merchant_url'],
		'type' => DOTPAY_PAYMENT_TYPE,
		'api_version' => DOTPAY_API_VERSION,
		// below additional optional parameters
		'firstname' => $wrapper->commerce_customer_billing->commerce_customer_address->first_name->value(),
		'lasttname' => $wrapper->commerce_customer_billing->commerce_customer_address->first_name->value(),
		'email'	=> $order->mail,
		'city'	=> $wrapper->commerce_customer_billing->commerce_customer_address->locality->value(),
		'postcode' => $wrapper->commerce_customer_billing->commerce_customer_address->postal_code->value(),
		'country' => $wrapper->commerce_customer_billing->commerce_customer_address->country->value(),
	);



	foreach ($data as $name => $value) {
		$form[$name] = array(
			'#type' => 'textfield',
			'#value' => $value,
		);
	}

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Redirect to Dotpay platform'),
	);

	commerce_dotpay_create_payment_transaction($data, $order, $payment_method);

	return $form;
}

function commerce_dotpay_create_payment_transaction($data, $order,$payment_method){
	$transaction = commerce_payment_transaction_new($payment_method['method_id'], $order->order_id);
	$transaction->instance_id = $payment_method['instance_id'];
	$transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
	$transaction->amount = $data['amount'];
	$transaction->currency_code = $data['currency'];
	commerce_payment_transaction_save($transaction);
}

function commerce_dotpay_get_and_validateLanguage(){
	global $language;
	$allowedLanguages = commerce_dotpay_languages();

	if (!array_key_exists($language->language, $allowedLanguages)){
		return 'en';

	}

	return $language->language;
};

function commerce_dotpay_languages(){
	return array(
		'pl' => t('Polish'),
		'en' => t('English'),
		'de' => t('German'),
		'it' => t('Italian'),
		'fr' => t('French'),
		'es' => t('Spanish'),
		'cz' => t('Czech'),
		'ru' => t('Russian'),
		'bg' => t('Bulgarian')
		);
}

